### ISSUE TITLE
Does not run on 5.2.0 or newer

### ISSUE THREAD

**Issue by Golutazem** [runsy/rcbows#2]
This mod does not activate for version 5.2.0 or the dev version since.
Perhaps the problem is because the
[Explosions mod does not activate](https://gitlab.com/ryvnf/explosions/-/issues/2)

**Comment by runsy** [comment]
Yes, activated but it is a API, not bows/arrows included. You need another mod to get the bows/arrows, as example farbbows.

**Comment by Golutazem** [comment]
Tested; appears to work with farbows.
